name: ip.yml
on:
  workflow_dispatch:

jobs:
  ip:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/byjoey/yx-tools:latest
    steps:
      - name: 筛选ip
        run: python3 /app/cloudflare_speedtest.py --mode beginner --count 1 --speed 1 --delay 2000 --region NRT

      - name: Upload Logs as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: result-csv  # 下载时的文件名
          path: ./result.csv             # 要保存的文件夹路径
