name: ip.yml
on:
  workflow_dispatch:

jobs:
  ip:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/byjoey/yx-tools:latest
    steps:
      - name: 筛选ip
        run: python3 /app/cloudflare_speedtest.py --mode beginner --count 50 --speed 5 --delay 200 --region NRT